---
title: "Several Sample Projects"
description: "Here are some examples of projects that have been created." 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r echo=FALSE, fig.align='center', message=FALSE, warning=FALSE, fig.width = 40, fig.asp =1}
library(htmlwidgets)
library(slickR)
nm <- c('Probability forecast of rainfall >200 mm/month mining concession','Mine site rainfall prediction ensemble','Multi-year rainfall climatology of mine sites','POC of ECMWF model at mine sites','RMSE of ECMWF model at mine sites','Time series of ECMWF model against observation','Provincial Deterministic Rainfall Prediction','Onset of dry season verification','Example of kriging geostatistic','The best rainfall model prediction every location','Anomaly Rainfall Prediction mining concession')
(slickR(nm, slideType = 'p') + settings(arrows = FALSE)) %synch% (slickR(obj = list.files("images/gallery_project/", full.names = T),height = "100%", width = "100%") + settings(dots = FALSE, autoplay = TRUE, speed = 250)) 
```
